tasks:
  - source: movie_rec_system/etl/extract.py
    product:
      nb: products/extract-pipeline.ipynb
      data: movie_rec_system/etl/movies_data.duckdb
  - source: movie_rec_system/etl/eda.ipynb
    static_analysis: disable
    product: 
      nb: products/eda-pipeline.ipynb